project_id = "rjgzvogrvvsejytqafih"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"

[functions.public-registration]
verify_jwt = false

[functions.training-automation]
verify_jwt = false